# Generated by Django 5.2.15 on 2026-06-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='payslips/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payroll')),
            ],
        ),
    ]
