# Generated by Django 5.2.15 on 2026-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
