# Generated by Django 5.2.15 on 2026-06-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_owners', models.PositiveIntegerField(default=1)),
                ('max_managers', models.PositiveIntegerField(default=0)),
                ('max_hr', models.PositiveIntegerField(default=0)),
                ('max_accountants', models.PositiveIntegerField(default=0)),
                ('max_employees', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
